# Generated by Django 5.0 on 2023-12-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menuapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="plat_du_jour",
            field=models.BooleanField(default=False),
        ),
    ]
