# Generated by Django 5.0 on 2024-01-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0002_alter_customer_location_alter_customer_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="location",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
