# Generated by Django 5.0 on 2023-12-29 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0001_initial"),
        ("ordersapp", "0003_alter_orderitem_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="price",
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("needed_for", models.DateTimeField()),
                ("paid", models.BooleanField()),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("notes", models.TextField(null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainapp.customer",
                    ),
                ),
                ("order_items", models.ManyToManyField(to="ordersapp.orderitem")),
            ],
        ),
    ]
