# Generated by Django 5.0 on 2023-12-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ordersapp", "0004_remove_orderitem_price_alter_orderitem_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
