# Generated by Django 5.0 on 2023-12-29 19:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ordersapp", "0006_alter_order_total_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="total_price",
        ),
    ]
