# Generated by Django 5.0 on 2024-01-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ordersapp", "0007_remove_order_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery",
            field=models.BooleanField(default=False),
        ),
    ]
