# Generated by Django 5.0 on 2024-01-02 13:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ordersapp", "0009_orderitem_linked_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="linked_order",
        ),
    ]
