# Generated by Django 5.0 on 2024-01-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ordersapp", "0011_orderitem_linked_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="linked_order",
        ),
        migrations.AlterField(
            model_name="order",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
